### ISSUE TITLE
Lab 1 Feedback

### ISSUE THREAD

**Issue by alanarnholt** [STT3851-Fall2019/lab1-chesnetjc#1]
Line 161 has Figure 1.1 hardcoded.  Should use something similar to:

To display the saved file as shown in Figure `\@ref(fig:ig)`, use the `include_graphics()` function from `knitr`.^[Use the argument `dpi = 96` inside `include_graphics()`.] 

with the following code chunk:

```{r, label = "ig", echo = FALSE, fig.cap = "Using `knitr::include_graphics()`"}
knitr::include_graphics("./JPG/YourFileName.jpeg", dpi = 96)
```

The rest looks great!

**Comment by chesnetjc** [comment]
@alanarnholt

**Comment by alanarnholt** [comment]
@chesnetjc Your footnote needs to have  backticks around dpi = 96 and incluce_graphics()...the rest is good.
